7341 Testing GridMap
OSLL/tiny-slam-ros-cpp pull request #22
Opened 2016-08-18 13:13 UTC by gam4ik

2016-09-10 09:50 UTC, HatlessFox commented on test/AutoExpandbleMap/AutoExpandble_map_utest.cpp
> +TEST(AutoExpandbleMapBaseTests, Right) {
Prepend test's name with "Expand_", e.g. Expand_Ringt and so on.

2016-09-10 09:52 UTC, HatlessFox commented on test/AutoExpandbleMap/AutoExpandble_map_utest.cpp
> +  bool flag = (param.height == 1)&&(param.width == 4);
the "flag" name is too generic, make it more specific. Apply this comment to the tests below.

2016-09-10 09:53 UTC, HatlessFox commented on test/AutoExpandbleMap/AutoExpandble_map_utest.cpp
> +  flag = (param.x == 0)&&(param.y == 0);
Surround && with spaces

2016-09-10 09:53 UTC, HatlessFox commented on test/AutoExpandbleMap/Map_test.h
> +struct HeWi {
HeWi is not a meaningful name

2016-09-10 09:56 UTC, HatlessFox commented on test/AutoExpandbleMap/Map_test.h
> +HeWi AutoExpandbleMap_Test(const DiscretePoint2D& Cell_coor) {
The name isn't meaningful. Why is it called "blahblah_Test"?

2016-09-10 09:57 UTC, HatlessFox commented on test/AutoExpandbleMap/Map_test.h
> +bool CellValue_test() {
Think about a name that reflects actions the method performs.

2016-09-10 09:57 UTC, HatlessFox commented on test/AutoExpandbleMap/Map_test.h
> +  for (i = x0; i < map.width(); ++i)
braces

2016-09-10 09:58 UTC, HatlessFox commented on test/AutoExpandbleMap/Map_test.h
> +  int x0 = map.map_center_x() - 1  - map.width();
combine with 34 via ternary operator

2016-09-26 11:09 UTC, HatlessFox commented on test/AutoExpandbleMap/Map_test.h
> +  int x0 = (map.map_center_x() == 0) ? 0 :
What does condition mean?

2016-09-26 11:10 UTC, HatlessFox commented on test/AutoExpandbleMap/Map_test.h
> +struct MapParam {
MapParam**s**

2016-09-26 11:10 UTC, HatlessFox commented on test/AutoExpandbleMap/Map_test.h
>    int height;
int height, width;
int x, y;

What does x mean?

2016-09-26 11:11 UTC, HatlessFox commented on test/AutoExpandbleMap/Map_test.h
>  GridMap map(std::shared_ptr<GridCellFactory>(new TinyBaseCellFactory));
Can we get rid of the global map variable?

2016-09-26 11:17 UTC, HatlessFox commented on test/AutoExpandbleMap/AutoExpandble_map_utest.cpp
> +  MapParam param = test_auto_expand({2, 0});
Have you tried to write a macro/function for the expansion verification code?
E.g. test_expansion(point, expected map params).
Have you also considered implementation of operator== for MapParams?

2016-09-26 11:18 UTC, HatlessFox requested changes
Minor fixes and clarifications are required.

2016-10-04 19:33 UTC, HatlessFox commented on test/AutoExpandbleMap/Map_test.h
> +             _height(height), _width(width), _map_center_x(map_center_x),
move  both _map_center_x/y to a new line

2016-10-04 19:34 UTC, HatlessFox commented on test/AutoExpandbleMap/Map_test.h
> +  return (left._height == right._height)&&(left._map_center_x == right._map_center_x)
) && ( (spaces)

2016-10-04 19:35 UTC, HatlessFox commented on test/AutoExpandbleMap/Map_test.h
> +  bool is_centershifting_x = (map.map_center_x() == 0),
Mb center_x_is_shifted?

2016-10-04 19:38 UTC, HatlessFox commented on test/AutoExpandbleMap/AutoExpandble_map_utest.cpp
> +bool is_succeed(const DiscretePoint2D& Cell_coor, MapParams expected_param) {
The name is not descriptive. Mb test_expansion_by_cell_update? And you can rm test_auto_expand (it seems redundant).

2016-10-04 19:38 UTC, HatlessFox commented on test/AutoExpandbleMap/Map_test.h
> +  param._height = map.height();
Use constructor, move the implementation to "is_succeed"

2016-10-04 19:39 UTC, HatlessFox commented
Comments where updated.

2016-10-06 05:28 UTC, HatlessFox approved these changes

2016-10-06 05:33 UTC, HatlessFox commented on test/AutoExpandbleMap/AutoExpandble_map_utest.cpp
> +bool test_expansion_by_cell_update(const DiscretePoint2D& Cell_coor, MapParams expected_param) {
The line has 80+ length. Split it and check the others.
Cell_coor -> cell_coord

2016-10-09 04:41 UTC, krinkin commented on test/AutoExpandbleMap/AutoExpandble_map_utest.cpp
> +bool test_expansion_by_cell_update(const DiscretePoint2D& Cell_coor, MapParams expected_param) {
Guys, i think we can increase line length limit up to 100. I mean {80-100] is OK

2016-12-12 11:07 UTC, merged